//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassManager.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PassManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dark.
        /// </summary>
        internal static string DarkThemeName {
            get {
                return ResourceManager.GetString("DarkThemeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на English.
        /// </summary>
        internal static string EnglishName {
            get {
                return ResourceManager.GetString("EnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на General.
        /// </summary>
        internal static string GeneralSettingName {
            get {
                return ResourceManager.GetString("GeneralSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All.
        /// </summary>
        internal static string GenerateModeAllName {
            get {
                return ResourceManager.GetString("GenerateModeAllName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Capital chars.
        /// </summary>
        internal static string GenerateModeCapitalCharsName {
            get {
                return ResourceManager.GetString("GenerateModeCapitalCharsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lower chars.
        /// </summary>
        internal static string GenerateModeLowercaseCharsName {
            get {
                return ResourceManager.GetString("GenerateModeLowercaseCharsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на None.
        /// </summary>
        internal static string GenerateModeNoneName {
            get {
                return ResourceManager.GetString("GenerateModeNoneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Numbers.
        /// </summary>
        internal static string GenerateModeNumberCharsName {
            get {
                return ResourceManager.GetString("GenerateModeNumberCharsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Special symbols.
        /// </summary>
        internal static string GenerateModeSpecialSymbolsName {
            get {
                return ResourceManager.GetString("GenerateModeSpecialSymbolsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Upper chars.
        /// </summary>
        internal static string GenerateModeUppercaseCharsName {
            get {
                return ResourceManager.GetString("GenerateModeUppercaseCharsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generate password.
        /// </summary>
        internal static string GeneratePasswordSettingName {
            get {
                return ResourceManager.GetString("GeneratePasswordSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generate from symbols.
        /// </summary>
        internal static string GenerateSymbolsName {
            get {
                return ResourceManager.GetString("GenerateSymbolsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key .
        /// </summary>
        internal static string KeyDefaultName {
            get {
                return ResourceManager.GetString("KeyDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Keys.
        /// </summary>
        internal static string KeysTabName {
            get {
                return ResourceManager.GetString("KeysTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Light.
        /// </summary>
        internal static string LightThemeName {
            get {
                return ResourceManager.GetString("LightThemeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        internal static string NameProperty {
            get {
                return ResourceManager.GetString("NameProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pass.
        /// </summary>
        internal static string PassPatchsBarName {
            get {
                return ResourceManager.GetString("PassPatchsBarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Passwords.
        /// </summary>
        internal static string PasswordViewName {
            get {
                return ResourceManager.GetString("PasswordViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Path.
        /// </summary>
        internal static string PathProperty {
            get {
                return ResourceManager.GetString("PathProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Russian.
        /// </summary>
        internal static string RussianName {
            get {
                return ResourceManager.GetString("RussianName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Safe file.
        /// </summary>
        internal static string SaveFileTitle {
            get {
                return ResourceManager.GetString("SaveFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на pass.bin.
        /// </summary>
        internal static string SavePassDefaultFolder {
            get {
                return ResourceManager.GetString("SavePassDefaultFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на password.bin.
        /// </summary>
        internal static string SavePassDefaultName {
            get {
                return ResourceManager.GetString("SavePassDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на pass.mps.
        /// </summary>
        internal static string SavePathDefaultName {
            get {
                return ResourceManager.GetString("SavePathDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select file.
        /// </summary>
        internal static string SelectFileTitle {
            get {
                return ResourceManager.GetString("SelectFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Setting.
        /// </summary>
        internal static string SettingTabName {
            get {
                return ResourceManager.GetString("SettingTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unspecified.
        /// </summary>
        internal static string UnspecifiedThemeName {
            get {
                return ResourceManager.GetString("UnspecifiedThemeName", resourceCulture);
            }
        }
    }
}
